// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backendSzM.Data;

#nullable disable

namespace backendSzM.Migrations
{
    [DbContext(typeof(UserDataDBContext))]
    [Migration("20260225075739_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("backendSzM.Models.BannedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BannedGmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BannedUsers");
                });

            modelBuilder.Entity("backendSzM.Models.Komment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Fogado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("KommentSzoveg")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Kommentalo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Komments");
                });

            modelBuilder.Entity("backendSzM.Models.Lobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TtType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("locationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("backendSzM.Models.LobbyCon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserDataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.HasIndex("UserDataId");

                    b.ToTable("LobbyCons");
                });

            modelBuilder.Entity("backendSzM.Models.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LobbyId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("backendSzM.Models.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserDataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserDataId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("backendSzM.Models.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TokenId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Warnings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TokenId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backendSzM.Models.Komment", b =>
                {
                    b.HasOne("backendSzM.Models.UserData", "userData")
                        .WithMany("Komments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("userData");
                });

            modelBuilder.Entity("backendSzM.Models.LobbyCon", b =>
                {
                    b.HasOne("backendSzM.Models.Lobby", "Lobby")
                        .WithMany("LobbyCons")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendSzM.Models.UserData", "UserData")
                        .WithMany("LobbyCons")
                        .HasForeignKey("UserDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("backendSzM.Models.Location", b =>
                {
                    b.HasOne("backendSzM.Models.Lobby", "Lobby")
                        .WithMany("Locations")
                        .HasForeignKey("LobbyId");

                    b.Navigation("Lobby");
                });

            modelBuilder.Entity("backendSzM.Models.Token", b =>
                {
                    b.HasOne("backendSzM.Models.UserData", "UserData")
                        .WithMany()
                        .HasForeignKey("UserDataId");

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("backendSzM.Models.UserData", b =>
                {
                    b.HasOne("backendSzM.Models.Token", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("backendSzM.Models.Lobby", b =>
                {
                    b.Navigation("LobbyCons");

                    b.Navigation("Locations");
                });

            modelBuilder.Entity("backendSzM.Models.UserData", b =>
                {
                    b.Navigation("Komments");

                    b.Navigation("LobbyCons");
                });
#pragma warning restore 612, 618
        }
    }
}
