// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backendSzM.Data;

#nullable disable

namespace backendSzM.Migrations
{
    [DbContext(typeof(UserDataDBContext))]
    partial class UserDataDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("backendSzM.Models.BannedUser", b =>
                {
                    b.Property<Guid>("BanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("IsBanned")
                        .HasColumnType("REAL");

                    b.Property<int>("Warnings")
                        .HasColumnType("INTEGER");

                    b.HasKey("BanId");

                    b.ToTable("BannedUsers");
                });

            modelBuilder.Entity("backendSzM.Models.Lobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TtType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lobby");
                });

            modelBuilder.Entity("backendSzM.Models.LobbyCon", b =>
                {
                    b.Property<Guid>("LobbyConId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LobbyConId");

                    b.HasIndex("LobbyId");

                    b.HasIndex("UserId");

                    b.ToTable("LobbyCon");
                });

            modelBuilder.Entity("backendSzM.Models.UserAuth", b =>
                {
                    b.Property<Guid>("UserAuthId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<float>("IsAdmin")
                        .HasColumnType("REAL");

                    b.HasKey("UserAuthId");

                    b.ToTable("UserAuth");
                });

            modelBuilder.Entity("backendSzM.Models.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BannedId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rep")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AuthId");

                    b.HasIndex("BannedId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backendSzM.Models.LobbyCon", b =>
                {
                    b.HasOne("backendSzM.Models.Lobby", "Lobby")
                        .WithMany("LobbyCons")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendSzM.Models.UserData", "UserData")
                        .WithMany("LobbyCons")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lobby");

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("backendSzM.Models.UserData", b =>
                {
                    b.HasOne("backendSzM.Models.UserAuth", "UserAuth")
                        .WithMany("UserDatas")
                        .HasForeignKey("AuthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendSzM.Models.BannedUser", "BannedUser")
                        .WithMany("UserDatas")
                        .HasForeignKey("BannedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BannedUser");

                    b.Navigation("UserAuth");
                });

            modelBuilder.Entity("backendSzM.Models.BannedUser", b =>
                {
                    b.Navigation("UserDatas");
                });

            modelBuilder.Entity("backendSzM.Models.Lobby", b =>
                {
                    b.Navigation("LobbyCons");
                });

            modelBuilder.Entity("backendSzM.Models.UserAuth", b =>
                {
                    b.Navigation("UserDatas");
                });

            modelBuilder.Entity("backendSzM.Models.UserData", b =>
                {
                    b.Navigation("LobbyCons");
                });
#pragma warning restore 612, 618
        }
    }
}
