// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backendSzM.Data;

#nullable disable

namespace backendSzM.Migrations
{
    [DbContext(typeof(UserDataDBContext))]
    partial class UserDataDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("backendSzM.Models.BannedUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Warnings")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BannedUsers");
                });

            modelBuilder.Entity("backendSzM.Models.Lobby", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Dm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerLimit")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("TtType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lobbies");
                });

            modelBuilder.Entity("backendSzM.Models.LobbyCon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LobbyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserDataId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LobbyId");

                    b.HasIndex("UserDataId");

                    b.ToTable("LobbyCons");
                });

            modelBuilder.Entity("backendSzM.Models.Token", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserDataId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserDataId");

                    b.ToTable("Tokens");
                });

            modelBuilder.Entity("backendSzM.Models.UserData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BannedId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BannedUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Hash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TokenId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BannedUserId");

                    b.HasIndex("TokenId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("backendSzM.Models.LobbyCon", b =>
                {
                    b.HasOne("backendSzM.Models.Lobby", "Lobby")
                        .WithMany("LobbyCons")
                        .HasForeignKey("LobbyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backendSzM.Models.UserData", "UserData")
                        .WithMany("LobbyCons")
                        .HasForeignKey("UserDataId");

                    b.Navigation("Lobby");

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("backendSzM.Models.Token", b =>
                {
                    b.HasOne("backendSzM.Models.UserData", "UserData")
                        .WithMany()
                        .HasForeignKey("UserDataId");

                    b.Navigation("UserData");
                });

            modelBuilder.Entity("backendSzM.Models.UserData", b =>
                {
                    b.HasOne("backendSzM.Models.BannedUser", "BannedUser")
                        .WithMany("UserDatas")
                        .HasForeignKey("BannedUserId");

                    b.HasOne("backendSzM.Models.Token", "Token")
                        .WithMany()
                        .HasForeignKey("TokenId");

                    b.Navigation("BannedUser");

                    b.Navigation("Token");
                });

            modelBuilder.Entity("backendSzM.Models.BannedUser", b =>
                {
                    b.Navigation("UserDatas");
                });

            modelBuilder.Entity("backendSzM.Models.Lobby", b =>
                {
                    b.Navigation("LobbyCons");
                });

            modelBuilder.Entity("backendSzM.Models.UserData", b =>
                {
                    b.Navigation("LobbyCons");
                });
#pragma warning restore 612, 618
        }
    }
}
